In [1]:
import csv
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

data = []

data_1 = 'RESIDIV_Vimala.csv'
data_2 = 'VV_RESIDIV_Vimala.csv'

with open(data_2, 'r') as csvfile:
    csvreader = csv.reader(csvfile, delimiter=',')
    next(csvreader)
    for row in csvreader:
        data.append(row)

In [2]:
data_unlabeled = pd.read_csv(data_2) 
data_labeled = pd.read_csv(data_1)

In [3]:
data_labeled.head()

Pas_ID       Født Oppdaget_når Age Død lever FIGO_stadium Substadium                    histologi gradering kreftform OVAgrade myometireinvasjon Cx_invasjon Karinvasjon Lymfekarinvasjon Lymfeknuter Tumor_str hist_nummer Primærbehandling Avsluttet_prim_beh Ant_ktr Beh_sykehus Ktr_ingen Ktr_priv Ktr_lok    Ktr_Uni Ktr_komb Ktr_fastlege Ktr_andre  Lengde_sympt_dager  Lengde_sympt_uker  Lengde_sympt_mnd  Symptomer_mindre_1mnd  TidSympt_2dic Oppdaget_pas Oppdaget_FL Oppdaget_Priv Oppdaget_Lok Oppdaget_Univ Oppdaget_Kir Oppdaget_annen Tidligere_kontakt Sympt_tilstede Sympt_blødning Sympt_smerter Sympt_vekttap Sympt_utflod Sympt_ascites Sympt_avføring Sympt_ileus Sympt_fatigue Sympt_vannlating Sympt_blodfeces Sympt_blodurin Sympt_anorexi Sympt_kakeksi Sympt_hudtumor sympt_luftveier Sympt_annet Verif_histo Histo_nummer          Histo_lab Verif_cytol Cytol_nummer  Cytol_lab Verif_MR Verif_CT Verif_RTH Verif_ABD_UL Verif_VAG_UL  ULverif Verif_Colon Verif_annet Lok_vagina Lok_bekken  \
0    5013  3/22/1937     1/1/2013  75                      I          C  (endometroid) adenocarcinom        G2    corpus                                    nei         nei                          nei                                kirurgi           3/1/2009       8   Stavanger       nei      nei     nei  Stavanger      nei          nei                             5                  0                 0                      1              1           ja         nei           nei          nei           nei          nei                               ja             ja            nei            ja           nei          nei           nei            nei         nei           nei              nei             nei            nei           nei           nei            nei             nei                     nei                                          ja         4156  Stavanger      nei       ja       nei           ja           ja        1         nei                    nei        nei   
1    1244   3/4/1941    12/1/2015  74        ja            I          B  (endometroid) adenocarcinom        G2    corpus                         M2         nei          ja                                            1503931          kirurgi           3/1/2015       3                   nei      nei     nei        nei                   nei                             0                  1                 0                      1              1           ja         nei           nei           ja            ja          nei                               ja             ja             ja            ja           nei          nei           nei            nei         nei            ja              nei             nei            nei           nei           nei            nei             nei                      ja        15160  OUS, DNR, Ullevål          ja     16000088                 nei       ja       nei           ja           ja        1         nei                     ja        nei   
2    2116  4/27/1934     8/1/2014  80                      I          C  (endometroid) adenocarcinom        G1    corpus                                                                                                819216  kir + cellegift           1/1/2009      16   Haukeland       nei       ja     nei        nei      nei          nei                             0                  0                 1                      0              1           ja         nei            ja          nei            ja          nei                               ja             ja            nei            ja           nei          nei           nei            nei         nei           nei              nei             nei            nei           nei           nei            nei             nei                      ja      1427589          Haukeland         nei                              nei       ja       nei           ja           ja        1         nei                    nei         ja   
3    5017  5/21/1935    11/1/20

In [4]:
data_unlabeled["Age"] = pd.to_numeric(data_unlabeled["Age"], errors='coerce')

In [5]:
data_unlabeled.sample(frac=1).head()

Pas_ID        Født Oppdaget_når   Age        Død lever  FIGO_stadium Substadium histologi gradering  kreftform OVAgrade myometireinvasjon Cx_invasjon Karinvasjon Lymfekarinvasjon Lymfeknuter Tumor_str hist_nummer  Primærbehandling Avsluttet_prim_beh Ant_ktr Beh_sykehus Ktr_ingen  Ktr_priv  Ktr_lok  Ktr_Uni Ktr_komb Ktr_fastlege Ktr_andre  Lengde_sympt_dager  Lengde_sympt_uker  Lengde_sympt_mnd  Symptomer_mindre_1mnd  TidSympt_2dic  Oppdaget_pas  Oppdaget_FL  Oppdaget_Priv  Oppdaget_Lok  Oppdaget_Univ  Oppdaget_Kir Oppdaget_annen Tidligere_kontakt  Sympt_tilstede  Sympt_blødning  Sympt_smerter  Sympt_vekttap  Sympt_utflod  Sympt_ascites  Sympt_avføring  Sympt_ileus  Sympt_fatigue  Sympt_vannlating  Sympt_blodfeces  Sympt_blodurin  Sympt_anorexi  Sympt_kakeksi  Sympt_hudtumor  sympt_luftveier Sympt_annet  Verif_histo Histo_nummer Histo_lab  Verif_cytol Cytol_nummer Cytol_lab  Verif_MR  Verif_CT  Verif_RTH  Verif_ABD_UL  Verif_VAG_UL  ULverif Verif_Colon Verif_annet  Lok_vagina  \
305   29005  11/25/1934     7/1/2012  77.0                1             1          2        14                    2                                                                                                                       1           6/1/1997      10          29         0         0        1        0        0            1                             0                  0                 6                      0              1             1            0              0             0              0             0                                1               1               0              0              0             0              1               1            0              0                 0                0               0              0              0               0                0                        1        19710         3            0                                0         1          0             0             0        0           0                       0   
89     2034  10/16/1942     1/1/2013  70.0                1             1          1         1         2          1                          1           2           3                            2                                       1           1/1/2012       4           2         0         1        0        0        0            0                             0                  0                 0                      0              0             0            0              1             0              1             0                                0               0               0              0              0             0              0               0            0              0                 0                0               0              0              0               0                0                        0                                   1      1300789         2         0         1          0             0             0        0           0                       1   
129    2002   5/22/1934     4/1/2012  77.0  3/20/2014                   3          2         1         2          1                          2                                                                                            2          10/1/2005      13           2         0         0        0        2        0            0                             0                  0                 0                      0              0             0            0              0             0              1             0                                0               0               0              0              0             0              0               0            0              0                 0                0               0              0              0               0                0                        0                                   0                                0         1          0             0             0        0           0                       0   
237    2069  

In [6]:
normal_input = data_unlabeled[["Sympt_blødning", "Sympt_smerter", "Sympt_ascites", "Sympt_fatigue"]]
the_best_input = data_unlabeled[["Sympt_blødning", "Sympt_smerter", "Sympt_vekttap", "Sympt_utflod", "Sympt_ascites", "Sympt_avføring", "Sympt_ileus", "Sympt_fatigue", "Sympt_vannlating", "Sympt_blodfeces", "Sympt_blodurin", "Sympt_anorexi", "Sympt_kakeksi", "Sympt_hudtumor", "sympt_luftveier"]]

In [7]:
from sklearn.neural_network import MLPClassifier

X = normal_input
y = data_unlabeled[["kreftform"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [8]:
X_train.head()

Sympt_blødning  Sympt_smerter  Sympt_ascites  Sympt_fatigue
431               0              0              0              0
276               0              1              0              0
413               0              1              0              0
577               0              0              0              0
18                1              0              0              0

In [112]:
clf = MLPClassifier(solver='lbfgs',
                    alpha=1e-5, 
                    hidden_layer_sizes=(5,5,3),
                    activation='logistic')
clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 13  62   0]
 [  0 132   0]
 [  2  16   0]]
0.6444444444444445
