In [3]:
%store -r data_unlabeled
%store -r data_labeled

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


In [10]:
normal_input = data_unlabeled[["Sympt_blødning", "Sympt_smerter", "Sympt_ascites", "Sympt_fatigue"]]
the_best_input = data_unlabeled[["Age", "Sympt_blødning", "Sympt_smerter", "Sympt_vekttap", "Sympt_utflod", "Sympt_ascites", "Sympt_avføring", "Sympt_ileus", "Sympt_fatigue", "Sympt_vannlating", "Sympt_blodfeces", "Sympt_blodurin", "Sympt_anorexi", "Sympt_kakeksi", "Sympt_hudtumor", "sympt_luftveier"]]

data_unlabeled.drop('kreftform', axis=1)

In [25]:
from sklearn.neural_network import MLPClassifier

X = the_best_input
y = data_unlabeled[["kreftform"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [26]:
clf = MLPClassifier(solver='lbfgs',
                    alpha=1e-5, 
                    hidden_layer_sizes=(100,),
                    activation='relu')
clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 25  43   2]
 [  5 130   2]
 [  8  10   0]]
0.6888888888888889
