In [1]:
%store -r normalized_df

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [6]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn import utils

tot_acc = 0
max_matrix = 0
max_accuracy = 0

min_matrix = 0
min_accuracy = 1

X = normalized_df.drop(['kreftform'], axis=1)
y = normalized_df[['kreftform']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

lab_enc = preprocessing.LabelEncoder()
encoded_y_train = lab_enc.fit_transform(y_train.values.ravel())
encoded_y_test = lab_enc.fit_transform(y_test.values.ravel())

for i in range(100):
    clf = RandomForestClassifier(n_estimators=100)

    clf.fit(X_train, encoded_y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(encoded_y_test, y_pred)
    
    if accuracy > max_accuracy:
        max_accuracy = accuracy
        max_matrix = confusion_matrix(encoded_y_test, y_pred)
        
    if accuracy < min_accuracy:
        min_accuracy = accuracy
        min_matrix = confusion_matrix(encoded_y_test, y_pred)
        
    tot_acc += accuracy
    tot = i+1
    mean = tot_acc/tot
    
print('Maximum')
print(max_accuracy, '\n', max_matrix)
print('----------------------------------')
print('Minimum')
print(min_accuracy, '\n', min_matrix)
print('----------------------------------')
print('mean accuracy:', mean)

Maximum
0.8844444444444445 
 [[ 48  18   0]
 [  3 132   0]
 [  2   3  19]]
----------------------------------
Minimum
0.84 
 [[ 44  22   0]
 [  4 131   0]
 [  4   6  14]]
----------------------------------
mean accuracy: 0.866933333333333
