In [1]:
%store -r data_unlabeled
%store -r data_labeled
%store -r preprocessed_df
%store -r imputed_data

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


In [3]:
normal_input = data_unlabeled[["Sympt_blødning", "Sympt_smerter", "Sympt_ascites", "Sympt_fatigue"]]
the_best_input = data_unlabeled[["Age", "Sympt_blødning", "Sympt_smerter", "Sympt_vekttap", "Sympt_utflod", "Sympt_ascites", "Sympt_avføring", "Sympt_ileus", "Sympt_fatigue", "Sympt_vannlating", "Sympt_blodfeces", "Sympt_blodurin", "Sympt_anorexi", "Sympt_kakeksi", "Sympt_hudtumor", "sympt_luftveier"]]

In [24]:
from sklearn import svm

X = imputed_data
y = data_unlabeled[["kreftform"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [25]:
clf = svm.SVC(gamma='scale')
clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0  66   0]
 [  0 145   0]
 [  0  14   0]]
0.6444444444444445
