In [2]:
%store -r normalized_df

In [3]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn import utils

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [67]:
from sklearn import svm

X = normalized_df.drop(['kreftform'], axis=1)
y = normalized_df[['kreftform']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

clf = svm.SVC(gamma='scale')

lab_enc = preprocessing.LabelEncoder()
encoded_y_train = lab_enc.fit_transform(y_train.values.ravel())
encoded_y_test = lab_enc.fit_transform(y_test.values.ravel())

clf.fit(X_train, encoded_y_train)
y_pred = clf.predict(X_test)

print(confusion_matrix(encoded_y_test, y_pred))
print(accuracy_score(encoded_y_test, y_pred))

[[ 38  25   0]
 [ 13 131   0]
 [  7   7   4]]
0.7688888888888888
