In [1]:
%store -r normalized_df

In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [40]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn import utils

X = normalized_df[['Sympt_blødning', 'Sympt_smerter', 'Sympt_ascites', 'Sympt_fatigue']]
y = normalized_df[['kreftform']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

clf = RandomForestClassifier(n_estimators=100)

lab_enc = preprocessing.LabelEncoder()
encoded_y_train = lab_enc.fit_transform(y_train.values.ravel())
encoded_y_test = lab_enc.fit_transform(y_test.values.ravel())

clf.fit(X_train, encoded_y_train)
y_pred = clf.predict(X_test)

print(confusion_matrix(encoded_y_test, y_pred))
print(accuracy_score(encoded_y_test, y_pred))

[[ 10  58   3]
 [  0 132   3]
 [  2  17   0]]
0.6311111111111111
