In [1]:
%store -r data_unlabeled
%store -r data_labeled
%store -r preprocessed_df
%store -r imputed_data

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


In [3]:
all_input = preprocessed_df
normal_input = data_unlabeled[["Sympt_blødning", "Sympt_smerter", "Sympt_ascites", "Sympt_fatigue"]]
the_best_input = data_unlabeled[["Age", "Sympt_blødning", "Sympt_smerter", "Sympt_vekttap", "Sympt_utflod", "Sympt_ascites", "Sympt_avføring", "Sympt_ileus", "Sympt_fatigue", "Sympt_vannlating", "Sympt_blodfeces", "Sympt_blodurin", "Sympt_anorexi", "Sympt_kakeksi", "Sympt_hudtumor", "sympt_luftveier"]]

data_unlabeled.drop('kreftform', axis=1)

In [3]:
from sklearn.neural_network import MLPClassifier

X = imputed_data
y = data_unlabeled[["kreftform"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [18]:
preprocessed_df['Lymfekarinvasjon']

0       
1       
2       
3       
4       
5       
6      3
7      3
8      3
9       
10      
11     3
12     2
13      
14      
15      
16      
17      
18      
19      
20      
21      
22      
23      
24      
25      
26      
27      
28     3
29     3
30      
31      
32      
33      
34      
35      
36     3
37      
38      
39      
40      
41      
42      
43      
44      
45      
46     3
47      
48     3
49      
50      
51     3
52     2
53     3
54      
55      
56      
57      
58      
59      
60      
61      
62      
63      
64      
65     3
66     3
67      
68     3
69     3
70     3
71     3
72      
73      
74      
75      
76      
77      
78      
79      
80     2
81      
82      
83      
84      
85      
86      
87      
88      
89      
90      
91      
92      
93     3
94      
95     3
96     3
97     3
98     3
99     3
100    2
101     
102     
103     
104     
105     
106    2
107     
108     
109     
110     
1

In [19]:
imputed_data['Lymfekarinvasjon']

0      2.7
1      2.7
2      2.7
3      2.7
4      2.7
5      2.7
6      3.0
7      3.0
8      3.0
9      2.7
10     2.7
11     3.0
12     2.0
13     2.7
14     2.7
15     2.7
16     2.7
17     2.7
18     2.7
19     2.7
20     2.7
21     2.7
22     2.7
23     2.7
24     2.7
25     2.7
26     2.7
27     2.7
28     3.0
29     3.0
30     2.7
31     2.7
32     2.7
33     2.7
34     2.7
35     2.7
36     3.0
37     2.7
38     2.7
39     2.7
40     2.7
41     2.7
42     2.7
43     2.7
44     2.7
45     2.7
46     3.0
47     2.7
48     3.0
49     2.7
50     2.7
51     3.0
52     2.0
53     3.0
54     2.7
55     2.7
56     2.7
57     2.7
58     2.7
59     2.7
60     2.7
61     2.7
62     2.7
63     2.7
64     2.7
65     3.0
66     3.0
67     2.7
68     3.0
69     3.0
70     3.0
71     3.0
72     2.7
73     2.7
74     2.7
75     2.7
76     2.7
77     2.7
78     2.7
79     2.7
80     2.0
81     2.7
82     2.7
83     2.7
84     2.7
85     2.7
86     2.7
87     2.7
88     2.7
89     2.7
90     2.7

In [59]:
clf = MLPClassifier(solver='lbfgs',
                    alpha=1e-5, 
                    activation='relu')
clf.fit(X_train, y_train.values.ravel())
y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 8 30 32]
 [10 60 62]
 [ 2 12  9]]
0.3422222222222222
